export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

export const CHANGE_SEARCH_CRITERIA = 'CHANGE_SEARCH_CRITERIA';
export const CLEAR_FILTERED = 'CLEAR_FILTERED';
